export const HOME_SCREEN = "HOME_SCREEN";
export const TESTIMONIAL_SCREEN = "TESTIMONIAL_SCREEN";
export const RECORD_SCREEN = "RECORD_SCREEN";
export const PREVIEW_SCREEN = "PREVIEW_SCREEN";
export const THANK_YOU_SCREEN = "THANK_YOU_SCREEN";
export const VIDEO_QUESTIONS_SCREEN = "VIDEO_QUESTIONS_SCREEN";

// Dispatch types
export const RESET_DATA = "RESET_DATA";
export const SET_TYPE = "SET_TYPE";
export const SET_URL = "SET_URL";
export const SET_URL_DURATION = "SET_URL_DURATION";
export const SET_STATUS = "SET_STATUS";
export const SET_SCREEN = "SET_SCREEN";
export const SET_AUDIO_PLAYING = "SET_AUDIO_PLAYING";

export const SET_CLIENT_NAME = "SET_CLIENT_NAME";
export const SET_CLIENT_EMAIL = "SET_CLIENT_EMAIL";
export const SET_CLIENT_COMPANY = "SET_CLIENT_COMPANY";

export const SET_THUMB_URL = "SET_THUMB_URL";

export const SET_INDEX = "Set_INDEX";
export const SET_RECORD_CHUKS = "SET_RECORD_CHUKS";
export const SET_QUESTION = "SET_QUESTION";
export const SET_QUESTION_URL = "SET_QUESTION_URL";
export const SET_QUESTION_THUMB_URL = "SET_QUESTION_THUMB_URL";
